CREATE TABLE rooms (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id    VARCHAR(128) NOT NULL UNIQUE,
    name       VARCHAR(255),
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_rooms_room_id ON rooms (room_id);
